refresh:
  name: Refresh Mateo data
  description: Force an immediate fetch from Mateo for all configured entries, or a single entry if entry_id is provided.
  fields:
    entry_id:
      name: Entry ID
      description: (Optional) Target a single config entry by its entry_id.
      required: false
      example: 1234567890abcdef
      selector:
        text: