name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt1-dev libjpeg-dev zlib1g-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy pytest pytest-cov homeassistant pytest-homeassistant-custom-component

      - name: Lint (ruff)
        run: ruff check .

      - name: Type check (mypy)
        run: mypy custom_components/mateo_meals

      - name: Run tests
        run: pytest

      - name: Collect coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: coverage-${{ matrix.python-version }}
            path: ./.coverage*

  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hassfest
        uses: home-assistant/actions/hassfest@master
